spring.application.name=banking-transaction-processor

# Database URL, username, and password
spring.datasource.url=jdbc:postgresql://localhost:5432/banking_process
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.default_schema=bpm

# JPA / Hibernate properties
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect