CREATE DATABASE banking_process
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
    
CREATE SCHEMA bpm
    AUTHORIZATION postgres;

CCREATE TABLE bpm.accounts (
    account_id numeric(5,0) PRIMARY KEY,
    balance NUMERIC(19,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS bpm.accounts
    OWNER to postgres;

CREATE TABLE bpm.transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id numeric(5,0),
    type VARCHAR(20),
    amount NUMERIC(19,2),
    reference_account_id numeric(5,0),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES bpm.accounts(account_id)
);

ALTER TABLE IF EXISTS bpm.transactions
    OWNER to postgres;
	
commit;
